// This file is generated by Gemini.
'use server';
/**
 * @fileOverview Flow for verifying community-submitted remedies.
 *
 * - verifyRemedy - Verifies the plausibility of a submitted plant remedy.
 * - VerifyRemedyInput - The input type for the verifyRemedy function.
 * - VerifyRemedyOutput - The return type for the verifyRemedy function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { gemini15Flash } from 'genkit/models';

const VerifyRemedyInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of the plant used in the remedy, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  plantName: z.string().describe('The name of the plant used in the remedy.'),
  remedyDescription: z.string().describe('A description of the remedy.'),
  language: z.string().describe('The language the remedy is described in.'),
  effectivenessRating: z
    .number()
    .min(1)
    .max(5)
    .describe('The effectiveness rating of the remedy (1-5).'),
});
export type VerifyRemedyInput = z.infer<typeof VerifyRemedyInputSchema>;

const VerifyRemedyOutputSchema = z.object({
  isPlausible: z
    .boolean()
    .describe(
      'Whether the submitted remedy is plausible based on the plant and description.'
    ),
  verificationNotes: z
    .string()
    .describe('Notes on the verification process and any issues found.'),
});
export type VerifyRemedyOutput = z.infer<typeof VerifyRemedyOutputSchema>;

export async function verifyRemedy(
  input: VerifyRemedyInput
): Promise<VerifyRemedyOutput> {
  return verifyRemedyFlow(input);
}

const verifyRemedyPrompt = ai.definePrompt({
  name: 'verifyRemedyPrompt',
  input: {schema: VerifyRemedyInputSchema},
  output: {schema: VerifyRemedyOutputSchema},
  model: gemini15Flash,
  prompt: `You are an AI assistant tasked with verifying the plausibility of plant-based remedies submitted by users.

You will receive information about the plant, a description of the remedy, and an effectiveness rating.
Your task is to determine if the remedy is plausible based on the information provided.

Consider the following factors when making your determination:

*   Does the remedy description align with common uses of the plant?
*   Is the remedy likely to be effective based on the description?
*   Does the provided photo match the description?
*   Are there any red flags or inconsistencies in the information?

Respond with whether the remedy is plausible or not, and provide notes on your verification process.

Plant Name: {{{plantName}}}
Remedy Description: {{{remedyDescription}}}
Effectiveness Rating: {{{effectivenessRating}}}
Photo: {{media url=photoDataUri}}
Language: {{{language}}}`,
});

const verifyRemedyFlow = ai.defineFlow(
  {
    name: 'verifyRemedyFlow',
    inputSchema: VerifyRemedyInputSchema,
    outputSchema: VerifyRemedyOutputSchema,
  },
  async input => {
    const {output} = await verifyRemedyPrompt(input);
    return output!;
  }
);
