// This file is generated by Gemini.
'use server';
/**
 * @fileOverview Flow for generating a remedy suggestion from an image.
 *
 * - suggestRemedyFromImage - Analyzes an image of a plant to suggest a remedy.
 * - SuggestRemedyFromImageInput - The input type for the suggestRemedyFromImage function.
 * - SuggestRemedyFromImageOutput - The return type for the suggestRemedyFromImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestRemedyFromImageInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of the plant for the remedy, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  plantName: z.string().describe('The name of the plant shown in the image.'),
});
export type SuggestRemedyFromImageInput = z.infer<
  typeof SuggestRemedyFromImageInputSchema
>;

const SuggestRemedyFromImageOutputSchema = z.object({
  suggestedDescription: z
    .string()
    .describe(
      'A detailed description of a common traditional remedy using this plant. Include preparation and usage instructions.'
    ),
  suggestedEffectiveness: z
    .number()
    .min(1)
    .max(5)
    .describe(
      'An estimated effectiveness rating (1-5) for the suggested remedy based on traditional knowledge.'
    ),
});
export type SuggestRemedyFromImageOutput = z.infer<
  typeof SuggestRemedyFromImageOutputSchema
>;

export async function suggestRemedyFromImage(
  input: SuggestRemedyFromImageInput
): Promise<SuggestRemedyFromImageOutput> {
  return remedySuggestionFlow(input);
}

const remedySuggestionPrompt = ai.definePrompt({
  name: 'remedySuggestionPrompt',
  input: {schema: SuggestRemedyFromImageInputSchema},
  output: {schema: SuggestRemedyFromImageOutputSchema},
  prompt: `You are an expert in traditional Indian herbal medicine (Ayurveda, folk medicine).
Analyze the provided image of a plant, identified as "{{plantName}}".

Based on the image and the plant name, your task is to:
1.  Propose a single, common, and safe traditional remedy associated with this plant.
2.  Write a clear and concise description for this remedy, including simple steps for preparation and how it is typically used.
3.  Provide an estimated effectiveness rating for this specific remedy on a scale of 1 to 5, where 5 is highly effective for its intended purpose.
4.  Do not invent uses. If the plant has no well-known remedies, state that in the description and provide a rating of 1.

Plant Name: {{{plantName}}}
Photo: {{media url=photoDataUri}}`,
});

const remedySuggestionFlow = ai.defineFlow(
  {
    name: 'remedySuggestionFlow',
    inputSchema: SuggestRemedyFromImageInputSchema,
    outputSchema: SuggestRemedyFromImageOutputSchema,
  },
  async input => {
    const {output} = await remedySuggestionPrompt(input);
    return output!;
  }
);
