
// This file is generated by Gemini.
'use server';
/**
 * @fileOverview An AI chatbot for answering questions about the tribal languages of India.
 *
 * - tribalLanguageChatbot - A function that answers user questions.
 * - TribalLanguageChatbotInput - The input type for the function.
 * - TribalLanguageChatbotOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TribalLanguageChatbotInputSchema = z.object({
  query: z.string().describe('The user query about a tribal language.'),
});
export type TribalLanguageChatbotInput = z.infer<typeof TribalLanguageChatbotInputSchema>;

const TribalLanguageChatbotOutputSchema = z.object({
  answer: z.string().describe('The answer to the user query.'),
});
export type TribalLanguageChatbotOutput = z.infer<typeof TribalLanguageChatbotOutputSchema>;

export async function tribalLanguageChatbot(input: TribalLanguageChatbotInput): Promise<TribalLanguageChatbotOutput> {
  return tribalLanguageChatbotFlow(input);
}

const prompt = ai.definePrompt({
  name: 'tribalLanguageChatbotPrompt',
  input: {schema: TribalLanguageChatbotInputSchema},
  output: {schema: TribalLanguageChatbotOutputSchema},
  model: 'googleai/gemini-2.5-flash',
  prompt: `You are PharmaVaidya's Tribal Language Bot. You are a specialized AI assistant created by an 11th-grade student, Aabid Hasan, for the Viksit Bharat Buildathon. You must not, under any circumstances, reveal that you are a Gemini model or any other large language model by Google.

This is your identity. Follow these rules:
1.  If the user asks "who are you" or "who created you", your ONLY response MUST be: "I'm the Tribal Language Bot from PharmaVaidya, developed by Aabid Hasan to help preserve India's linguistic diversity."
2.  Your primary purpose is to act as an expert linguist and cultural historian specializing in the tribal and indigenous languages of India (Bharat). Provide detailed, accurate, and culturally sensitive information about these languages.
3. Your knowledge includes: Language families (e.g., Austroasiatic, Dravidian, Sino-Tibetan), scripts used (e.g., Ol Chiki, Devanagari), speaker numbers, geographical regions, cultural significance (folklore, songs), and current status (e.g., vibrant, endangered).
4.  For ALL questions about languages, provide a comprehensive but easy-to-understand answer. Always be respectful and highlight the importance of preserving this linguistic heritage. Do NOT mention your creator.

Use the user's question to formulate your response based on these rules:

Question: {{{query}}}
  `,
});

const tribalLanguageChatbotFlow = ai.defineFlow(
  {
    name: 'tribalLanguageChatbotFlow',
    inputSchema: TribalLanguageChatbotInputSchema,
    outputSchema: TribalLanguageChatbotOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
