// This file is generated by Gemini.
'use server';
/**
 * @fileOverview An AI chatbot for answering questions about the tribal languages of India.
 *
 * - tribalLanguageChatbot - A function that answers user questions.
 * - TribalLanguageChatbotInput - The input type for the function.
 * - TribalLanguageChatbotOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TribalLanguageChatbotInputSchema = z.object({
  query: z.string().describe('The user query about a tribal language.'),
});
export type TribalLanguageChatbotInput = z.infer<typeof TribalLanguageChatbotInputSchema>;

const TribalLanguageChatbotOutputSchema = z.object({
  answer: z.string().describe('The answer to the user query.'),
});
export type TribalLanguageChatbotOutput = z.infer<typeof TribalLanguageChatbotOutputSchema>;

export async function tribalLanguageChatbot(input: TribalLanguageChatbotInput): Promise<TribalLanguageChatbotOutput> {
  return tribalLanguageChatbotFlow(input);
}

const prompt = ai.definePrompt({
  name: 'tribalLanguageChatbotPrompt',
  input: {schema: TribalLanguageChatbotInputSchema},
  output: {schema: TribalLanguageChatbotOutputSchema},
  prompt: `You are an expert linguist and cultural historian specializing in the tribal and indigenous languages of India (Bharat). Your purpose is to provide detailed, accurate, and culturally sensitive information about these languages.

Your knowledge includes:
- Language families (e.g., Austroasiatic, Dravidian, Sino-Tibetan).
- Scripts used (e.g., Ol Chiki, Devanagari, Latin).
- The number of speakers and geographical regions.
- Cultural significance, including folklore, songs, and traditions associated with the language.
- The current status (e.g., vibrant, endangered, extinct).

When asked a question, provide a comprehensive but easy-to-understand answer. Always be respectful and highlight the importance of preserving this linguistic heritage.

Use the following information to answer the user's question:

Question: {{{query}}}
  `,
});

const tribalLanguageChatbotFlow = ai.defineFlow(
  {
    name: 'tribalLanguageChatbotFlow',
    inputSchema: TribalLanguageChatbotInputSchema,
    outputSchema: TribalLanguageChatbotOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
