
import type { CommunityRemedy } from './types';

export const initialRemedies: Omit<CommunityRemedy, "id">[] = [
  {
    plantName: 'Neem',
    remedyDescription: 'A paste of neem leaves can be applied to minor cuts and skin irritations. It acts as a natural antiseptic and helps in faster healing.',
    language: 'English',
    effectivenessRating: 4,
    submittedAt: new Date(Date.now() - 86400000 * 2).toISOString(), // 2 days ago
    upvotes: 15,
    downvotes: 1,
    isPlausible: true,
    verificationNotes: 'This is a well-known and plausible use of Neem leaves, which have documented antiseptic properties.',
    photoUrl: 'https://images.unsplash.com/photo-1704380881202-ead38b580d9a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHxuZWVtJTIwdHJlZXxlbnwwfHx8fDE3NjE0NTc1MTR8MA&ixlib=rb-4.1.0&q=80&w=1080',
  },
  {
    plantName: 'Tulsi (Holy Basil)',
    remedyDescription: 'Chewing 3-4 raw tulsi leaves in the morning on an empty stomach can help boost immunity and reduce seasonal cough and cold.',
    language: 'English',
    effectivenessRating: 5,
    submittedAt: new Date(Date.now() - 86400000 * 5).toISOString(), // 5 days ago
    upvotes: 28,
    downvotes: 0,
    isPlausible: true,
    verificationNotes: 'The use of Tulsi for immunity and respiratory health is a cornerstone of Ayurvedic tradition and is considered highly plausible.',
    photoUrl: 'https://images.unsplash.com/photo-1696397279839-a2b8785c2113?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHx0dWxzaSUyMHBsYW50fGVufDB8fHx8MTc2MTUyODA3Mnww&ixlib=rb-4.1.0&q=80&w=1080',
  },
  {
    plantName: 'Turmeric',
    remedyDescription: 'For a sore throat, gargle with warm salt water mixed with a pinch of turmeric powder. It helps reduce inflammation.',
    language: 'English',
    effectivenessRating: 4,
    submittedAt: new Date(Date.now() - 86400000 * 1).toISOString(), // 1 day ago
    upvotes: 12,
    downvotes: 0,
    isPlausible: true,
    verificationNotes: 'Turmeric\'s anti-inflammatory properties are well-documented. Using it in a warm saline gargle for sore throats is a common and plausible home remedy.',
    photoUrl: 'https://images.unsplash.com/photo-1702041295331-840d4d9aa7c9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxUdXJtZXJpY3xlbnwwfHx8fDE3NjE1NDI0NDF8MA&ixlib=rb-4.1.0&q=80&w=1080',
  },
  {
    plantName: 'Aloe Vera',
    remedyDescription: 'Apply fresh Aloe Vera gel directly on mild sunburns. It provides a cooling effect and helps moisturize the skin.',
    language: 'English',
    effectivenessRating: 5,
    submittedAt: new Date(Date.now() - 86400000 * 10).toISOString(), // 10 days ago
    upvotes: 45,
    downvotes: 2,
    isPlausible: true,
    verificationNotes: 'The application of Aloe Vera gel for sunburns is a widely accepted and scientifically supported remedy due to its soothing and hydrating properties.',
    photoUrl: 'https://images.unsplash.com/photo-1520038410233-7141be7e6f97?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxBbG9lJTIwVmVyYSUyMHBsYW50fGVufDB8fHx8MTc2MjE5NjU3Nnww&ixlib=rb-4.1.0&q=80&w=1080',
  },
   {
    plantName: 'Ginger',
    remedyDescription: 'Ginger tea, made by boiling fresh ginger slices in water, is excellent for relieving nausea and indigestion.',
    language: 'English',
    effectivenessRating: 5,
    submittedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    upvotes: 22,
    downvotes: 1,
    isPlausible: true,
    verificationNotes: 'Ginger is a well-known carminative and antiemetic. Its use for nausea and digestive issues is highly plausible and supported by numerous studies.',
    photoUrl: "https://images.unsplash.com/photo-1620989339031-a3875320516a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxnaW5nZXIlMjByb290fGVufDB8fHx8MTc2MjE5OTQ0Nnww&ixlib=rb-4.1.0&q=80&w=1080",
  },
  {
    plantName: 'Ashwagandha',
    remedyDescription: 'Take a spoonful of Ashwagandha root powder with warm milk before bedtime to promote restful sleep and reduce stress.',
    language: 'English',
    effectivenessRating: 4,
    submittedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    upvotes: 18,
    downvotes: 1,
    isPlausible: true,
    verificationNotes: 'Ashwagandha is a renowned adaptogen. Using it to manage stress and improve sleep is a primary application in Ayurveda and is considered plausible.',
    photoUrl: 'https://images.unsplash.com/photo-1565113423207-a492a62a70fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxhc2h3YWdhbmRoYSUyMHBsYW50fGVufDB8fHx8MTc2MTQ1NzUxM3ww&ixlib=rb-4.1.0&q=80&w=1080',
  },
  {
    plantName: 'Brahmi',
    remedyDescription: 'Make a paste of Brahmi leaves and apply it on the scalp. It helps in nourishing the hair roots and keeps the head cool.',
    language: 'Hindi',
    effectivenessRating: 3,
    submittedAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    upvotes: 9,
    downvotes: 3,
    isPlausible: true,
    verificationNotes: 'While Brahmi is more known for cognitive benefits, its use in hair preparations is common in traditional practices. The remedy is plausible.',
    photoUrl: 'https://images.unsplash.com/photo-1693380140795-745c219de8c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxicmFobWl8ZW58MHx8fHwxNzYxNTQyMDU3fDA&ixlib=rb-4.1.0&q=80&w=1080',
  },
  {
    plantName: 'Amla (Indian Gooseberry)',
    remedyDescription: 'Regular consumption of Amla juice in the morning is great for eyesight and skin glow due to its high Vitamin C content.',
    language: 'English',
    effectivenessRating: 5,
    submittedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    upvotes: 31,
    downvotes: 1,
    isPlausible: true,
    verificationNotes: 'Amla is one of the richest sources of Vitamin C. Its benefits for immunity, skin, and overall health are well-established and make this remedy very plausible.',
    photoUrl: 'https://images.unsplash.com/photo-1676043967557-2b70d9facd71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxhbWxhfGVufDB8fHx8MTc2MTU0MjA3M3ww&ixlib=rb-4.1.0&q=80&w=1080',
  },
  {
    plantName: 'Peppermint',
    remedyDescription: 'Inhaling the steam from water infused with a few peppermint leaves can help clear nasal congestion.',
    language: 'English',
    effectivenessRating: 4,
    submittedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    upvotes: 14,
    downvotes: 0,
    isPlausible: true,
    verificationNotes: 'The menthol in peppermint acts as a natural decongestant. Steam inhalation is a common method for this purpose, making the remedy plausible.',
    photoUrl: "https://images.unsplash.com/photo-1596495691452-f2acedfd808c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxwZXBwZXJtaW50JTIwbGVhdmVzfGVufDB8fHx8MTc2MjE5OTQ4OHww&ixlib=rb-4.1.0&q=80&w=1080",
  },
  {
    plantName: 'Giloy',
    remedyDescription: 'Crush Giloy stem, boil in water until it reduces to half. Drink this decoction to fight chronic fever.',
    language: 'Santhali',
    effectivenessRating: 4,
    submittedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    upvotes: 8,
    downvotes: 2,
    isPlausible: true,
    verificationNotes: 'Giloy (Tinospora cordifolia) is known as "Amrita" and is famous in Ayurveda for its antipyretic properties. The remedy is highly plausible.',
    photoUrl: 'https://images.unsplash.com/photo-1721115328229-23a5abc9a3e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxUaW5vc3BvcmElMjBjb3JkaWZvbGlhfGVufDB8fHx8MTc2MjE5ODY4N3ww&ixlib=rb-4.1.0&q=80&w=1080',
  },
  {
    plantName: 'Tomato',
    remedyDescription: 'Applying tomato juice on the skin can cause severe rashes and is not recommended for skincare.',
    language: 'English',
    effectivenessRating: 1,
    submittedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    upvotes: 2,
    downvotes: 10,
    isPlausible: false,
    verificationNotes: 'The remedy describes a negative effect. While tomato is acidic and could irritate sensitive skin, this submission appears to be a warning rather than a remedy. The AI flags it as not a plausible positive remedy.',
    photoUrl: "https://images.unsplash.com/photo-1582284540020-8acbe03fec79?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHx0b21hdG9lcyUyMG9uJTIwdmluZXxlbnwwfHx8fDE3NjIyMDAyOTl8MA&ixlib=rb-4.1.0&q=80&w=1080",
  },
  {
    plantName: 'Moringa',
    remedyDescription: 'Moringa leaf powder can be added to dals and curries to increase their nutritional value without significantly altering the taste.',
    language: 'English',
    effectivenessRating: 5,
    submittedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    upvotes: 19,
    downvotes: 0,
    isPlausible: true,
    verificationNotes: 'Moringa is a superfood, rich in nutrients. Incorporating the powder into daily meals is a very common and plausible method to boost nutrition.',
    photoUrl: 'https://images.unsplash.com/photo-1632349944365-5933c09f3032?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxtb3JpbmdhJTIwb2xlaWZlcmF8ZW58MHx8fHwxNzYyMTk4NjU3fDA&ixlib=rb-4.1.0&q=80&w=1080',
  }
];
